[package]
name = "rust-wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spacetimedb-bindgen = { path = "../spacetimedb-bindgen" }
spacetimedb-bindings = { path = "../spacetimedb-bindings" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
