[workspace]
members = ["crates/bitcraft-mini", "crates/bitcraft-mini-expand"]
# members = ["crates/bitcraft-mini"]
default-members = ["crates/bitcraft-mini"]

[profile.release]
opt-level = 's'
lto = true
