[workspace]
members = ["crates/bitcraft-mini"]
# exclude = ["crates/rust-wasm-goal", "crates/rust-wasm-output", "crates/rust-wasm"]
default-members = ["crates/bitcraft-mini"]

[profile.release]
opt-level = 's'
lto = true
