[package]
name = "rust-wasm-goal"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html\

[lib]
crate-type = ["cdylib"]

[dependencies]
spacetimedb-bindings = { path = "../spacetimedb-bindings" }
backtrace = "0.3.64"
