[package]
name = "rust-wasm-test"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html\

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.81"
spacetimedb-bindings = { path = "../spacetimedb-bindings" }
spacetimedb-bindgen = { path = "../spacetimedb-bindgen" }
backtrace = "0.3.64"